/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-11 06:10:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.memberDTO.tm_memberDTO;

public final class N1_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.memberDTO.tm_memberDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/N1_main.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/overlay.css\" />\r\n");
      out.write("    <title>main</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"side_bar\">\r\n");
      out.write("		<b>My Real Travel in GwangJu </b>\r\n");
      out.write("		\r\n");
      out.write("		");
 tm_memberDTO dto = (tm_memberDTO)session.getAttribute("dto");
		
		if (dto == null) {
      out.write("\r\n");
      out.write("		<button onClick=\"location.href='Join.jsp'\">회원가입</button>\r\n");
      out.write("		<button onClick=\"location.href='Login.jsp'\">로그인</button>\r\n");
      out.write("		");
} else { 
      out.write("\r\n");
      out.write("		<button onClick=\"location.href='tm_LogoutCon'\">로그아웃</button>\r\n");
      out.write("		");
} 
      out.write("\r\n");
      out.write("	</div> \r\n");
      out.write("    <div id=\"side_all\">\r\n");
      out.write("        <div id=\"side_one\">\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul class=\"side_menu\">\r\n");
      out.write("                	<!-- onClick=\"window.location.reload()\" -->\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N1_main.jsp'\"><a href=\"#\" >검색</a></button></li>\r\n");
      out.write("					");
if (dto == null) {
      out.write("\r\n");
      out.write("					<li><button class = \"side_button\" onClick=\"location.href='mypage_logout.jsp'\"><a href=\"#\" >여행계획</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='mypage_logout.jsp'\"><a href=\"#\" >My</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='mypage_logout.jsp'\"><a href=\"#\" >SNS</a></button></li>\r\n");
      out.write("					");
} else {
      out.write("\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N2_travelplan1.jsp'\"><a href=\"#\" >여행계획</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N3_mypage_login_1bookmark1.jsp'\"><a href=\"#\" >My</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N5_sns.jsp'\"><a href=\"#\" >SNS</a></button></li>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"side_two\">\r\n");
      out.write("            <input type=\"text\" id=\"search_keyword_query\" placeholder=\"검색어 입력\">\r\n");
      out.write("            <button id=\"search_keyword_query_button\" onClick=\"MapSearch()\"><img src=\"./img/search.png\"></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"side_three\">\r\n");
      out.write("           <ul>\r\n");
      out.write("               <li><button onClick=\"MapData('restaurant')\">\r\n");
      out.write("                   <img src=\"./img/restaurant.png\">\r\n");
      out.write("                   <p>맛집</p>\r\n");
      out.write("                </button></li>\r\n");
      out.write("               <li><button onClick=\"MapData('tour')\">\r\n");
      out.write("					<img src=\"./img/location.png\">\r\n");
      out.write("                   <p>관광지</p>\r\n");
      out.write("                </button></li>\r\n");
      out.write("               <li><button onClick=\"MapData('cafe')\">\r\n");
      out.write("	                <img src=\"./img/cafe.png\">\r\n");
      out.write("	                <p>카페</p>\r\n");
      out.write("                </button></li>\r\n");
      out.write("				<li><button onClick=\"MapData('accomodation')\">\r\n");
      out.write("					<img src=\"./img/hotel.png\">\r\n");
      out.write("					<p>숙박</p>\r\n");
      out.write("				</button></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"side_four\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("<script src=\"./assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("    	function MapSearch() {\r\n");
      out.write("    		\r\n");
      out.write("    		$.ajax({\r\n");
      out.write("				url : 'MapSearchCon',\r\n");
      out.write("				type : 'get',\r\n");
      out.write("				data : { \r\n");
      out.write("					'keyword' : $('#search_keyword_query').val()\r\n");
      out.write("				},\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				success : function(res) {\r\n");
      out.write("					\r\n");
      out.write("					console.log(res)\r\n");
      out.write("					\r\n");
      out.write("					if (res == null) {\r\n");
      out.write("						\r\n");
      out.write("						alert('검색어를 입력하세요.');\r\n");
      out.write("						\r\n");
      out.write("					} else {\r\n");
      out.write("\r\n");
      out.write("						$('#side_four').html('');	\r\n");
      out.write("						\r\n");
      out.write("						let table = \"\";\r\n");
      out.write("						\r\n");
      out.write("						for(let i = 0; i < res.length; i++) {\r\n");
      out.write("						\r\n");
      out.write("							if (res[i].map_type == \"숙박시설\") {\r\n");
      out.write("								res[i].map_img = null;\r\n");
      out.write("							}	\r\n");
      out.write("						\r\n");
      out.write("							table += '<ul class=\"tour_list\">';\r\n");
      out.write("							table += '<table width=\"400\" height=\"100\" align=\"left\">';\r\n");
      out.write("							table += '<tr><td><h3><a href=\"#\" class =\"local_find\" value = '+i+'>'\r\n");
      out.write("							+ res[i].map_name + '</a></h3></td>';\r\n");
      out.write("							if (res[i].map_img == \"null\" || res[i].map_img == null) {\r\n");
      out.write("								table += '<th rowspan=\"4\"><img src=\"./phm_img/No_Image.png\" width=\"100\", height=\"100\" align=\"right\" style=\"border:1px solid #c8c8c8;\"></th></tr>';\r\n");
      out.write("							} else {\r\n");
      out.write("								table += '<th rowspan=\"4\"><img src=\"' + res[i].map_img + '\" width=\"100\", height=\"100\" align=\"right\"></th></tr>';\r\n");
      out.write("							}\r\n");
      out.write("							table += '<tr><td><div class=\"map_name style=\"display:none;\"\">'\r\n");
      out.write("								+ res[i].map_name + '</div></td></tr>';\r\n");
      out.write("							if (res[i].map_stars == 0) {\r\n");
      out.write("								table += '<tr><td>★ : <a class=\"map_stars\">평가중</div></td></tr>';\r\n");
      out.write("							} else {\r\n");
      out.write("								table += '<tr><td>★ : <a class=\"map_stars\">'\r\n");
      out.write("									+ res[i].map_stars + '</div></td></tr>';\r\n");
      out.write("							}\r\n");
      out.write("							table += '<tr><td><div class=\"map_addr\">'\r\n");
      out.write("								+ res[i].map_addr + '</div></td></tr>';\r\n");
      out.write("							if (res[i].map_img == \"null\") {\r\n");
      out.write("								table += '<div class =\"map_img\" style=\"display:none;\">./phm_img/No_Image.png</div>';\r\n");
      out.write("							} else {\r\n");
      out.write("								table += '<div class =\"map_img\" style=\"display:none;\">'\r\n");
      out.write("									+ res[i].map_img + '</div>';\r\n");
      out.write("							}\r\n");
      out.write("							table += '<div class =\"map_latitude\" style=\"display:none;\">'\r\n");
      out.write("										+ res[i].map_latitude + '</div>';\r\n");
      out.write("							table += '<div class =\"map_longtitude\" style=\"display:none;\">'\r\n");
      out.write("									+ res[i].map_longtitude + '</div>';\r\n");
      out.write("							table += '</ul>';\r\n");
      out.write("							table += '<hr width=\"400\" align=\"left\">';\r\n");
      out.write("							}\r\n");
      out.write("							$('#side_four').append(table);\r\n");
      out.write("							}\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert('검색실패');\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("    		\r\n");
      out.write("    	}\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("<!-- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->    \r\n");
      out.write("	<div id=\"map\" style=\"width: 73.3%; height: 100vh; float: right;\"></div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"./assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function MapData(MapType) {\r\n");
      out.write("			$('#side_four').html('');\r\n");
      out.write("			$.ajax({\r\n");
      out.write("						url : \"MapdataCon\",\r\n");
      out.write("						type : \"get\",\r\n");
      out.write("						data : {\r\n");
      out.write("							\"type\":MapType\r\n");
      out.write("						},\r\n");
      out.write("						dataType : \"json\",\r\n");
      out.write("						success : function(res) {\r\n");
      out.write("							console.log(res);\r\n");
      out.write("							let table = \"\";\r\n");
      out.write("							for (let i = 0; i < res.length; i++) {\r\n");
      out.write("								table += '<ul class=\"tour_list\">';\r\n");
      out.write("								table += '<table width=\"400\" height=\"100\" align=\"left\">';\r\n");
      out.write("								table += '<tr><td><h3><a href=\"#\" class =\"local_find\" value = '+i+'>'\r\n");
      out.write("								+ res[i].map_name + '</a></h3></td>';\r\n");
      out.write("								if (res[i].map_img == \"null\" || res[i].map_img == null) {\r\n");
      out.write("									table += '<th rowspan=\"4\"><img src=\"./phm_img/No_Image.png\" width=\"100\", height=\"100\" align=\"right\" style=\"border:1px solid #c8c8c8;\"></th></tr>';\r\n");
      out.write("								} else {\r\n");
      out.write("									table += '<th rowspan=\"4\"><img src=\"' + res[i].map_img + '\" width=\"100\", height=\"100\" align=\"right\"></th></tr>';\r\n");
      out.write("								}\r\n");
      out.write("								table += '<tr><td><div class=\"map_name style=\"display:none;\"\">'\r\n");
      out.write("									+ res[i].map_name + '</div></td></tr>';\r\n");
      out.write("								if (res[i].map_stars == 0) {\r\n");
      out.write("									table += '<tr><td>★ : <a class=\"map_stars\">평가중</div></td></tr>';\r\n");
      out.write("								} else {\r\n");
      out.write("									table += '<tr><td>★ : <a class=\"map_stars\">'\r\n");
      out.write("										+ res[i].map_stars + '</div></td></tr>';\r\n");
      out.write("								}\r\n");
      out.write("								table += '<tr><td><div class=\"map_addr\">'\r\n");
      out.write("									+ res[i].map_addr + '</div></td></tr>';\r\n");
      out.write("								if (res[i].map_img == \"null\") {\r\n");
      out.write("									table += '<div class =\"map_img\" style=\"display:none;\">./phm_img/No_Image.png</div>';\r\n");
      out.write("								} else {\r\n");
      out.write("									table += '<div class =\"map_img\" style=\"display:none;\">'\r\n");
      out.write("										+ res[i].map_img + '</div>';\r\n");
      out.write("								}\r\n");
      out.write("								table += '<div class =\"map_latitude\" style=\"display:none;\">'\r\n");
      out.write("										+ res[i].map_latitude + '</div>';\r\n");
      out.write("								table += '<div class =\"map_longtitude\" style=\"display:none;\">'\r\n");
      out.write("										+ res[i].map_longtitude + '</div>';\r\n");
      out.write("								table += '</ul>';\r\n");
      out.write("								table += '<hr width=\"400\" align=\"left\">';\r\n");
      out.write("							}\r\n");
      out.write("							$('#side_four').append(table)\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						},\r\n");
      out.write("						error : function() {\r\n");
      out.write("							alert(\"요청 실패!\")\r\n");
      out.write("						}\r\n");
      out.write("\r\n");
      out.write("					})\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=31e189d0d305a85663770a625b11688d&libraries=services\"></script>\r\n");
      out.write("	<script>	\r\n");
      out.write("		let ovr=[];\r\n");
      out.write("		let marker_storage = [];\r\n");
      out.write("		let latitude = \"\";\r\n");
      out.write("		let longtitude = \"\";\r\n");
      out.write("		var content=\"\";\r\n");
      out.write("		var positions=[];\r\n");
      out.write("		\r\n");
      out.write("		//ajax로 가져온 데이터를 다시 지도api에 전송하기 위한 이벤트\r\n");
      out.write("		$(document).on(\"click\",\".local_find\",function() {\r\n");
      out.write("			var index = $(this).attr('value');\r\n");
      out.write("			latitude_bring = document.getElementsByClassName('map_latitude');\r\n");
      out.write("			longtitude_bring = document.getElementsByClassName('map_longtitude');\r\n");
      out.write("			latitude = latitude_bring[index].innerHTML;\r\n");
      out.write("			longtitude = longtitude_bring[index].innerHTML;\r\n");
      out.write("			map_name = document.getElementsByClassName('map_name')[index].innerHTML;\r\n");
      out.write("			map_stars = document.getElementsByClassName('map_stars')[index].innerHTML;\r\n");
      out.write("			map_addr = document.getElementsByClassName('map_addr')[index].innerHTML;\r\n");
      out.write("			map_img = document.getElementsByClassName('map_img')[index].innerHTML;\r\n");
      out.write("			\r\n");
      out.write("			positions.push({title: map_name, \r\n");
      out.write("		        latlng: new kakao.maps.LatLng(latitude, longtitude)})\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			panTo();		// 지도 중심을 부드럽게 이동시킵니다\r\n");
      out.write("			displayMarker(positions, map_name, map_stars, map_addr, map_img);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		var mapContainer = document.getElementById('map'); // 지도를 표시할 div \r\n");
      out.write("		mapOption = {\r\n");
      out.write("			center : new kakao.maps.LatLng(35.11070531999631,\r\n");
      out.write("					126.87780481325912), // 지도의 중심좌표 - 스마트인재개발원\r\n");
      out.write("			level : 3	// 지도의 확대 레벨\r\n");
      out.write("		};\r\n");
      out.write("		// 지도를 생성합니다    \r\n");
      out.write("		var map = new kakao.maps.Map(mapContainer, mapOption);\r\n");
      out.write("		\r\n");
      out.write("		function panTo() {\r\n");
      out.write("			// 이동할 위도 경도 위치를 생성합니다 \r\n");
      out.write("			var moveLatLon = new kakao.maps.LatLng(latitude, longtitude);\r\n");
      out.write("\r\n");
      out.write("			// 지도 중심을 부드럽게 이동시킵니다\r\n");
      out.write("			// 만약 이동할 거리가 지도 화면보다 크면 부드러운 효과 없이 이동합니다\r\n");
      out.write("			map.panTo(moveLatLon);\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function displayMarker(positions, map_name, map_stars, map_addr, map_img) {\r\n");
      out.write("			console.log(positions);\r\n");
      out.write("			for(var i =0; i <positions.length; i++){\r\n");
      out.write("				// 마커를 생성하고 지도에 표시합니다\r\n");
      out.write("				var marker = new kakao.maps.Marker({\r\n");
      out.write("					map : map,\r\n");
      out.write("					position: positions[i].latlng, // 마커를 표시할 위치\r\n");
      out.write("			        //title : positions[i].title, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다\r\n");
      out.write("					level : 3\r\n");
      out.write("				});\r\n");
      out.write("				marker_storage.push(marker);\r\n");
      out.write("				\r\n");
      out.write("				var content = '<div class=\"wrap\">'\r\n");
      out.write("					+ '   		 <div class=\"info\">'\r\n");
      out.write("					+ '        		<div class=\"title\">'\r\n");
      out.write("					+ 					map_name\r\n");
      out.write("					+ '            	<div class=\"close\" onclick=\"closeOverlay('+i+')\" title=\"닫기\"></div>'\r\n");
      out.write("					+ '        		</div>'\r\n");
      out.write("					+ '        		<div class=\"body\">'\r\n");
      out.write("					+ '            		<div class=\"img\">'\r\n");
      out.write("					+ '                		<img src=\"'+map_img+'\" width=\"73\" height=\"70\">'\r\n");
      out.write("					+ '          		</div>'\r\n");
      out.write("					+ '             	<div class=\"desc\">'\r\n");
      out.write("					+ '               		<div class=\"ellipsis\">'\r\n");
      out.write("					+ 							map_addr \r\n");
      out.write("					+'						</div>'\r\n");
      out.write("					+'                		<div class=\"jibun ellipsis\">별점 : '+map_stars+'</div>'  \r\n");
      out.write("					+'						<div align=\"right\" style=\"padding:10px;\"><button onclick=\"favorites(\\''+map_name+'\\')\" id=\"move_button\" style=\\\"width:60px; margin-right:10px;\\\">즐겨찾기</buttton>   '					\r\n");
      out.write("					+' 						<button onclick=\"location.href=\\'N2_travelplan1.jsp\\'\" id=\"move_button\">계획세우러가기</button></div> ' \r\n");
      out.write("					//+'                	<div><a href=\"https://www.kakaocorp.com/main\" target=\"_blank\" class=\"link\">홈페이지</a></div>' \r\n");
      out.write("					+ '            		</div>' \r\n");
      out.write("					+ '       		</div>'\r\n");
      out.write("					+ '    		</div>' \r\n");
      out.write("					+ '		</div>';\r\n");
      out.write("				\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("			// 커스텀 오버레이를 생성해줍니다.\r\n");
      out.write("			var overlay = new kakao.maps.CustomOverlay({\r\n");
      out.write("				content : content,\r\n");
      out.write("				map : map,\r\n");
      out.write("				position : marker.getPosition()\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// 커스텀 오버레이를 닫기 위해 호출되는 함수입니다 \r\n");
      out.write("			// 전역변수에 overlay담기\r\n");
      out.write("			ovr.push(overlay)\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			// 마커를 클릭했을 때 커스텀 오버레이를 표시합니다\r\n");
      out.write("			kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("				overlay.setMap(map);\r\n");
      out.write("			});\r\n");
      out.write("			//kakao.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("			//	closeOverlay();\r\n");
      out.write("			//});\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function plan_page(){\r\n");
      out.write("			location.href=\"N2_travelplan1.jsp\";\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		function closeOverlay(i) {\r\n");
      out.write("			//console.log(typeof i);\r\n");
      out.write("			//console.log(\"ovr : \", ovr[i])\r\n");
      out.write("			console.log(marker_storage[i])\r\n");
      out.write("			ovr[i].setMap(null);\r\n");
      out.write("			marker_storage[i].setMap(null);\r\n");
      out.write("			\r\n");
      out.write(" 			/*let a = positions[i]\r\n");
      out.write("			for(let j = 0; j < positions.length; j++) {\r\n");
      out.write("				  if(positions[j] == a)  {\r\n");
      out.write("				    positions.splice(j, 1);\r\n");
      out.write("				  }\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			console.log('삭제결과>>',positions);\r\n");
      out.write("			///return marker_storage */\r\n");
      out.write("		}\r\n");
      out.write("		function favorites(map_name){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"favorite_insertCon\",\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"map_name\":map_name\r\n");
      out.write("				},\r\n");
      out.write("				success : function(res) {\r\n");
      out.write("					if(res=='1'){\r\n");
      out.write("						alert(\"즐겨찾기 성공!\");\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"요청 실패!\")\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
