/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-04 05:50:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.snsDTO.tm_snsDTO;
import java.util.ArrayList;
import com.memberDAO.tm_memberDAO;
import com.snsDAO.tm_snsDAO;
import com.memberDTO.tm_memberDTO;

public final class N3_005fmypage_005flogin_005f3myinfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.snsDAO.tm_snsDAO");
    _jspx_imports_classes.add("com.snsDTO.tm_snsDTO");
    _jspx_imports_classes.add("com.memberDAO.tm_memberDAO");
    _jspx_imports_classes.add("com.memberDTO.tm_memberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/N4_mypage_login_3myinfo.css\" />\r\n");
      out.write("<title>N4_mypage_login_3myinfo</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".filebox label {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding-left: 6px;\r\n");
      out.write("	padding-top: 4px;\r\n");
      out.write("	padding-right: 6px;\r\n");
      out.write("	padding-bottom: 4px;\r\n");
      out.write("	color: BLACK;\r\n");
      out.write("	font-size: inherit;\r\n");
      out.write("	font-family: 'NanumBarunGothic';\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	line-height: normal;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("	background-color: #CDFBE4;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	border: 1px solid #fff;\r\n");
      out.write("	border-radius: .25em;\r\n");
      out.write("	-webkit-transition: background-color 0.2s;\r\n");
      out.write("	transition: background-color 0.2s;\r\n");
      out.write("	padding-top: 4px;\r\n");
      out.write("	padding-right: 6px;\r\n");
      out.write("	padding-bottom: 4px;\r\n");
      out.write("	padding-right: 6px;\r\n");
      out.write("	padding-bottom: 4px;\r\n");
      out.write("	padding-bottom: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox label:hover {\r\n");
      out.write("	background-color: #6ed36e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox label:active {\r\n");
      out.write("	background-color: #367c36;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox input[type=\"file\"] {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 1px;\r\n");
      out.write("	height: 1px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: -1px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	clip: rect(0, 0, 0, 0);\r\n");
      out.write("	border: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");

		tm_memberDTO memberdto = (tm_memberDTO) session.getAttribute("dto");
		tm_memberDAO memberdao = new tm_memberDAO();
		tm_snsDAO snsdao = new tm_snsDAO();
		ArrayList<tm_snsDTO> list = new ArrayList<tm_snsDTO>();
		list = snsdao.searchMy(memberdto.getMb_id());

		int snsCount = snsdao.snsCount(memberdto.getMb_id());
	
      out.write("\r\n");
      out.write("	<div id=\"side_bar\">\r\n");
      out.write("		<b>My Real Travel in GwangJu </b>\r\n");
      out.write("		<button onClick=\"location.href='tm_LogoutCon'\">로그아웃</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"side_all\">\r\n");
      out.write("		<div id=\"side_one\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul class=\"side_menu\">\r\n");
      out.write("					<!-- onClick=\"window.location.reload()\" -->\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N1_main.jsp'\">\r\n");
      out.write("							<a href=\"#\">검색</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N2_travelplan1.jsp'\">\r\n");
      out.write("							<a href=\"#\">여행계획</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N3_mypage_login_1bookmark1.jsp'\">\r\n");
      out.write("							<a href=\"#\">My</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N5_sns.jsp'\">\r\n");
      out.write("							<a href=\"#\">SNS</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_two\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><button class=\"side_button\"\r\n");
      out.write("						onClick=\"location.href='N3_mypage_login_1bookmark1.jsp'\">내계획</button></li>\r\n");
      out.write("				<li><button class=\"side_button\"\r\n");
      out.write("						onClick=\"location.href='N3_mypage_login_2mynews.jsp'\">내소식</button></li>\r\n");
      out.write("				<li><button class=\"side_button\"\r\n");
      out.write("						onClick=\"location.href='N3_mypage_login_3myinfo.jsp'\">내정보</button></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_three\" style=\"height: 250px\">\r\n");
      out.write("			<div id=\"profile_img\">\r\n");
      out.write("				<div>\r\n");
      out.write("					<img src=\"tm_upload/");
      out.print(memberdto.getMb_img());
      out.write("\"\r\n");
      out.write("						onerror=\"this.src=/tm_upload/4949.jpg\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<form action=\"imgChangeCon\" method=\"post\"\r\n");
      out.write("					enctype=\"multipart/form-data\">\r\n");
      out.write("					<div class=\"filebox\">\r\n");
      out.write("						<label for=\"file\">이미지 변경</label> <input type=\"file\" id=\"file\"\r\n");
      out.write("							name=\"imgChange\" accept=\"image/*\" style=\"visibility:\"\"hidden\"}}>\r\n");
      out.write("						<label for=\"btn\">확인</label>\r\n");
      out.write("						<button id=\"btn\" type=\"submit\" style=\"display: none\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"profile_info\">\r\n");
      out.write("				<table>\r\n");
      out.write("					<colgroup>\r\n");
      out.write("						<col style=\"width: 40%;\">\r\n");
      out.write("					</colgroup>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>닉네임</td>\r\n");
      out.write("						<td><b>");
      out.print(memberdto.getMb_nickname());
      out.write("</b></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>게시물</td>\r\n");
      out.write("						<td><b>");
      out.print(snsCount);
      out.write("</b></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>팔로워</td>\r\n");
      out.write("						<td><b>");
      out.print(memberdto.getMb_follower());
      out.write("</b></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>팔로우</td>\r\n");
      out.write("						<td><b>");
      out.print(memberdto.getMb_follow());
      out.write(" </b></td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"galley\">\r\n");
      out.write("			");

				for (tm_snsDTO i : list) {
				System.out.println(i.getTb_file());
			
      out.write("\r\n");
      out.write("			<a href=\"tm_SelectOne?tb_seq=");
      out.print(i.getTb_seq());
      out.write("\"><img\r\n");
      out.write("				src=\"tm_upload/");
      out.print(i.getTb_file());
      out.write("\"\r\n");
      out.write("				style=\"float: left; width: 150px; height: 150px; padding:5px\"></a>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_five\"></div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->\r\n");
      out.write("	<div id=\"map\" style=\"width: 73.3%; height: 100vh; float: right;\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"./assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=31e189d0d305a85663770a625b11688d&libraries=services\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		var mapContainer = document.getElementById('map'); // 지도를 표시할 div \r\n");
      out.write("		mapOption = {\r\n");
      out.write("			center : new kakao.maps.LatLng(35.11070531999631,\r\n");
      out.write("					126.87780481325912), // 지도의 중심좌표 - 스마트인재개발원\r\n");
      out.write("			level : 3\r\n");
      out.write("		// 지도의 확대 레벨\r\n");
      out.write("		};\r\n");
      out.write("		// 지도를 생성합니다    \r\n");
      out.write("		var map = new kakao.maps.Map(mapContainer, mapOption);\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
