/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-04 06:07:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class N3_005fmypage_005flogin_005f2mynews_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"./assets/css/N4_mypage_login_2mynews.css\" />\r\n");
      out.write("	<title>N4_mypage_login_2mynews</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"side_bar\">\r\n");
      out.write("		<b>My Real Travel in GwangJu </b>\r\n");
      out.write("		<button onClick=\"location.href='tm_LogoutCon'\">로그아웃</button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"side_all\">\r\n");
      out.write("		<div id=\"side_one\">\r\n");
      out.write("			<nav>\r\n");
      out.write("                <ul class=\"side_menu\">\r\n");
      out.write("                    <!-- onClick=\"window.location.reload()\" -->\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N1_main.jsp'\"><a href=\"#\" >검색</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N2_travelplan1.jsp'\"><a href=\"#\" >여행계획</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N3_mypage_login_1bookmark1.jsp'\"><a href=\"#\" >My</a></button></li>\r\n");
      out.write("                    <li><button class = \"side_button\" onClick=\"location.href='N5_sns.jsp'\"><a href=\"#\" >SNS</a></button></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_two\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><button class = \"side_button\" onClick=\"location.href='N3_mypage_login_1bookmark1.jsp'\">내 계획</button></li>\r\n");
      out.write("				<li><button class = \"side_button\" onClick=\"location.href='N3_mypage_login_2mynews.jsp'\">내소식</button></li>\r\n");
      out.write("				<li><button class = \"side_button\" onClick=\"location.href='N3_mypage_login_3myinfo.jsp'\">내정보</button></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_three\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_four\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"side_five\">\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"./assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		window.onload = function eventLog() {\r\n");
      out.write("\r\n");
      out.write("			$\r\n");
      out.write("			.ajax({\r\n");
      out.write("				url : 'eventLogCon',\r\n");
      out.write("				type : 'post',\r\n");
      out.write("				data : {\r\n");
      out.write("					'conID' : \"");
 out.print(session.getAttribute("conID")); 
      out.write("\"\r\n");
      out.write("				},\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				success : function(res) {\r\n");
      out.write("					\r\n");
      out.write("					console.log(res)\r\n");
      out.write("					\r\n");
      out.write("					if (res.length == 0) {\r\n");
      out.write("						table = '';\r\n");
      out.write("						table += '<br>'\r\n");
      out.write("						table += '<h3 align=\"center\">새로운 소식이 없습니다.</h3>';\r\n");
      out.write("						$('#side_three').append(table);\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					for (let i = 0; i < res.length; i++) {\r\n");
      out.write("						\r\n");
      out.write("						table = ''\r\n");
      out.write("						\r\n");
      out.write("						if (res[i].log_type == \"likes\") {\r\n");
      out.write("						\r\n");
      out.write("							table += '<br>';\r\n");
      out.write("							table += '<table width=\"450\" height=\"70\" align=\"center\">';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							if (res[i].mb_img == null) {\r\n");
      out.write("								table += '<td rowspan=\"2\" width=\"20%\"><img src=\"./phm_img/default_profile.png\" width=\"50\" height=\"50\" style=\"border:1px solid #c8c8c8; border-radius:70%;\"></td>';	\r\n");
      out.write("							} else {\r\n");
      out.write("								table += '<td rowspan=\"2\" width=\"20%\"><img src=\"tm_upload/' + res[i].mb_img + '\" width=\"50\" height=\"50\" style=\"border-radius:70%;\"></td>';\r\n");
      out.write("							}\r\n");
      out.write("							table += '<td><b>' + res[i].mb_nickname + '</b></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td>회원님의 게시글에 좋아요를 보냈습니다.</td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '</table>';\r\n");
      out.write("							table += '<hr width=\"450\" align=\"center\">';\r\n");
      out.write("							\r\n");
      out.write("							$('#side_three').append(table);\r\n");
      out.write("							\r\n");
      out.write("						} else if (res[i].log_type == \"follower\") {\r\n");
      out.write("							\r\n");
      out.write("							table += '<br>';\r\n");
      out.write("							table += '<table width=\"450\" height=\"70\" align=\"center\">';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							if (res[i].mb_img == null) {\r\n");
      out.write("								table += '<td rowspan=\"2\" width=\"20%\"><img src=\"./phm_img/default_profile.png\" width=\"50\" height=\"50\" style=\"border:1px solid #c8c8c8; border-radius:70%;\"></td>';	\r\n");
      out.write("							} else {\r\n");
      out.write("								table += '<td rowspan=\"2\" width=\"20%\"><img src=\"tm_upload/' + res[i].mb_img + '\" width=\"50\" height=\"50\" style=\"border-radius:70%;\"></td>';\r\n");
      out.write("							}\r\n");
      out.write("							table += '<td><b>' + res[i].mb_nickname + '</b></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td>회원님을 팔로우하기 시작했습니다.</td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '</table>';\r\n");
      out.write("							table += '<hr width=\"450\" align=\"center\">';\r\n");
      out.write("							\r\n");
      out.write("							$('#side_three').append(table);\r\n");
      out.write("							\r\n");
      out.write("						} else if (res[i].log_type == \"insert\") {\r\n");
      out.write("							\r\n");
      out.write("							table += '<br>';\r\n");
      out.write("							table += '<table width=\"450\" height=\"70\" align=\"center\">';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td><b>새로운 계획이 등록되었습니다.</b></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td>내 계획에서 확인하세요!</td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '</table>';\r\n");
      out.write("							table += '<hr width=\"450\" align=\"center\">';\r\n");
      out.write("							\r\n");
      out.write("							$('#side_three').append(table);\r\n");
      out.write("						}\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert('검색실패');\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("<!-- --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->    \r\n");
      out.write("	<div id=\"map\" style=\"width: 73.3%; height: 100vh; float: right;\"></div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"./assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=31e189d0d305a85663770a625b11688d&libraries=services\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		var mapContainer = document.getElementById('map'); // 지도를 표시할 div \r\n");
      out.write("		mapOption = {\r\n");
      out.write("			center : new kakao.maps.LatLng(35.11070531999631,\r\n");
      out.write("					126.87780481325912), // 지도의 중심좌표 - 스마트인재개발원\r\n");
      out.write("			level : 3	// 지도의 확대 레벨\r\n");
      out.write("		};\r\n");
      out.write("		// 지도를 생성합니다    \r\n");
      out.write("		var map = new kakao.maps.Map(mapContainer, mapOption);\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
