/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-04 06:35:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.memberDAO.tm_memberDAO;
import com.memberDTO.tm_memberDTO;
import com.snsDTO.tm_snsDTO;
import java.util.ArrayList;
import com.snsDAO.tm_snsDAO;

public final class N5_005fsns_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1640737927496L));
    _jspx_dependants.put("jar:file:/C:/Users/smhrd/Desktop/jsp_servlet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Travel_Map/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.snsDAO.tm_snsDAO");
    _jspx_imports_classes.add("com.memberDAO.tm_memberDAO");
    _jspx_imports_classes.add("com.snsDTO.tm_snsDTO");
    _jspx_imports_classes.add("com.memberDTO.tm_memberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/N5_sns.css\" />\r\n");
      out.write("<title>N5_sns</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"header\">\r\n");
      out.write("		<b>My Real Travel in GwangJu </b>\r\n");
      out.write("		");

			tm_memberDTO dto = (tm_memberDTO)session.getAttribute("dto");
			if (dto != null) {
		
      out.write("\r\n");
      out.write("		<button onClick=\"location.href='tm_LogoutCon'\">로그아웃</button>\r\n");
      out.write("		");

			} else {
		
      out.write("\r\n");
      out.write("		<button>로그인</button>\r\n");
      out.write("		");

			}
		
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");

		tm_snsDAO dao = new tm_snsDAO();
		tm_memberDAO memberdao = new tm_memberDAO();
		ArrayList<tm_snsDTO> list = dao.selectAll();
		tm_memberDTO memberdto = null;
		ArrayList<String> imgList = new ArrayList<String>();
		request.setAttribute("list", list);
		String nick = null;
		
	
      out.write("\r\n");
      out.write("	<div class=\"side_all\">\r\n");
      out.write("		<div class=\"side_one\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul class=\"side_menu\">\r\n");
      out.write("					<!-- onClick=\"window.location.reload()\" -->\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N1_main.jsp'\">\r\n");
      out.write("							<a href=\"#\">검색</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N2_travelplan1.jsp'\">\r\n");
      out.write("							<a href=\"#\">여행계획</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N3_mypage_login_1bookmark1.jsp'\">\r\n");
      out.write("							<a href=\"#\">My</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("					<li><button class=\"side_button\"\r\n");
      out.write("							onClick=\"location.href='N5_sns.jsp'\">\r\n");
      out.write("							<a href=\"#\">SNS</a>\r\n");
      out.write("						</button></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"side_two\">\r\n");
      out.write("\r\n");
      out.write("			<select id=\"type\"\r\n");
      out.write("				style=\"width: 90px; height: 47px; float: left; margin-left: 10px; margin-right: -10px; border: 1px solid #52C999; border-radius: 3px;\">\r\n");
      out.write("				<option value=\"title\">제목</option>\r\n");
      out.write("				<option value=\"user\">사용자</option>\r\n");
      out.write("			</select> <input type=\"text\" id=\"search_keyword_query\" placeholder=\" 검색어 입력\"\r\n");
      out.write("				style=\"width: 300px; height: 36px;\">\r\n");
      out.write("			<button id=\"search_keyword_query_button\" onClick='snsSearch()'>\r\n");
      out.write("				<img src=\"./img/search.png\">\r\n");
      out.write("			</button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"side_three\">\r\n");
      out.write("			");

				for (tm_snsDTO i : list) {
					nick = memberdao.searchNick(i.getMb_id());
			
      out.write("\r\n");
      out.write("			<div class=\"sns_feed\">\r\n");
      out.write("				<div class=\"profile\">\r\n");
      out.write("					<a href=\"#\" class=\"profile_img\"><img\r\n");
      out.write("						src=\"tm_upload/");
      out.print(memberdao.imgMemberSelect(i.getMb_id()));
      out.write("\"></a>\r\n");
      out.write("					<a href=\"tm_selectMember?mb_id=");
      out.print(i.getMb_id());
      out.write("\" class=\"user_nick\">");
      out.print(nick);
      out.write("</a>\r\n");
      out.write("					<div style=\"float:right; margin:20px;\">\r\n");
      out.write("						<a href=\"N_travelplanCon?mb_id=");
      out.print(i.getMb_id());
      out.write("&t_title=");
      out.print(i.getT_title() );
      out.write("\" style=\"font-size:12px; color:cornflowerblue;\">TravelPlan</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"trvel_pictures\">\r\n");
      out.write("					<a href=\"tm_SelectOne?tb_seq=");
      out.print(i.getTb_seq());
      out.write("\"> <img\r\n");
      out.write("						class=\"item\" src=\"tm_upload/");
      out.print(i.getTb_file());
      out.write("\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mini\">\r\n");
      out.write("					<button>\r\n");
      out.write("						<img src=\"./img/heart_tung.png\">\r\n");
      out.write("					</button>\r\n");
      out.write("					<h4>");
      out.print(i.getTb_likes());
      out.write("</h4>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"trvel_writing\">\r\n");
      out.write("					<h4 style=\"margin-left:23px; margin-bottom:8px\">");
      out.print(i.getTb_title());
      out.write("</h4>\r\n");
      out.write("					<p style=\"margin-top:5px\">");
      out.print(i.getTb_content());
      out.write("<p>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

				}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- -------------------------------------------------------------------------------------------------------------------------------------- -->\r\n");
      out.write("	<div id=\"map\" style=\"width: 73.3%; height: 100vh; float: right;\"></div>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"./assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function snsSearch() {\r\n");
      out.write("\r\n");
      out.write("			if ($('#type').val() == 'user') {\r\n");
      out.write("\r\n");
      out.write("				$\r\n");
      out.write("						.ajax({\r\n");
      out.write("							url : 'UserSearchCon',\r\n");
      out.write("							type : 'get',\r\n");
      out.write("							data : {\r\n");
      out.write("								'keyword' : $('#search_keyword_query').val()\r\n");
      out.write("							},\r\n");
      out.write("							dataType : 'json',\r\n");
      out.write("							success : function(res) {\r\n");
      out.write("\r\n");
      out.write("								console.log(res)\r\n");
      out.write("\r\n");
      out.write("								if (res == null) {\r\n");
      out.write("\r\n");
      out.write("									alert('검색어를 입력하세요.');\r\n");
      out.write("\r\n");
      out.write("								} else {\r\n");
      out.write("\r\n");
      out.write("									$('.side_three').html('');\r\n");
      out.write("\r\n");
      out.write("									let table = \"\";\r\n");
      out.write("\r\n");
      out.write("									for (let i = 0; i < res.length; i++) {\r\n");
      out.write("\r\n");
      out.write("										table += '<br>'\r\n");
      out.write("										table += '<table width=\"300\" height=\"100\" align=\"center\">';\r\n");
      out.write("										if (res[i].mb_img == null) {\r\n");
      out.write("											table += '<th rowspan=\"4\"><img src=\"./phm_img/default_profile.png\" width=\"100\", height=\"100\" align=\"left\" onClick='\r\n");
      out.write("													+ \"'snsDetail()'\"\r\n");
      out.write("													+ ' style=\"cursor:pointer; border:1px solid #c8c8c8;\"></th>';\r\n");
      out.write("										} else {\r\n");
      out.write("											table += '<th rowspan=\"4\"><img src=\"tm_upload/'\r\n");
      out.write("													+ res[i].mb_img\r\n");
      out.write("													+ '\" width=\"100\", height=\"100\" align=\"left\" onClick='\r\n");
      out.write("													+ \"'snsDetail()'\"\r\n");
      out.write("													+ ' style=\"cursor:pointer\"></th>';\r\n");
      out.write("										}\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										table += '<td>닉네임</td>'\r\n");
      out.write("										table += '<td><b id=\"user_nickname\">'\r\n");
      out.write("												+ res[i].mb_nickname\r\n");
      out.write("												+ '</b></td>';\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										table += '<td>팔로우</td>'\r\n");
      out.write("										table += '<td><b id=\"user_follow\">'\r\n");
      out.write("												+ res[i].mb_follow\r\n");
      out.write("												+ '</b></td>';\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										table += '<td>팔로워</td>'\r\n");
      out.write("										table += '<td><b id=\"user_follower\">'\r\n");
      out.write("												+ res[i].mb_follower\r\n");
      out.write("												+ '</b></td>';\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("										table += '</table>';\r\n");
      out.write("										table += '<br>';\r\n");
      out.write("										table += '<hr width=\"400\" align=\"center\">';\r\n");
      out.write("										table += '<a id=\"user_id\" style=\"display:none;\">'\r\n");
      out.write("												+ res[i].mb_id + '</a>';\r\n");
      out.write("										if (res[i].mb_img == null) {\r\n");
      out.write("											table += '<a id=\"user_image\" style=\"display:none;\"><img src=\"./phm_img/default_profile.png\" width=\"100\", height=\"100\" align=\"left\" style=\"border:1px solid #c8c8c8;\"></a\">';\r\n");
      out.write("										} else {\r\n");
      out.write("											table += '<a id=\"user_image\" style=\"display:none;\"><img src=\"tm_upload/' + res[i].mb_img + '\" width=\"100\", height=\"100\" align=\"left\"></a>';\r\n");
      out.write("										}\r\n");
      out.write("\r\n");
      out.write("									}\r\n");
      out.write("									$('.side_three').append(table);\r\n");
      out.write("								}\r\n");
      out.write("							},\r\n");
      out.write("							error : function() {\r\n");
      out.write("								alert('검색실패');\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("			} else {\r\n");
      out.write("\r\n");
      out.write("				$\r\n");
      out.write("						.ajax({\r\n");
      out.write("							url : 'TitleSearchCon',\r\n");
      out.write("							type : 'get',\r\n");
      out.write("							data : {\r\n");
      out.write("								'keyword' : $('#search_keyword_query').val()\r\n");
      out.write("							},\r\n");
      out.write("							dataType : 'json',\r\n");
      out.write("							success : function(res) {\r\n");
      out.write("\r\n");
      out.write("								console.log(res)\r\n");
      out.write("\r\n");
      out.write("								if (res == null) {\r\n");
      out.write("\r\n");
      out.write("									alert('검색어를 입력하세요.');\r\n");
      out.write("\r\n");
      out.write("								} else {\r\n");
      out.write("\r\n");
      out.write("									$('.side_three').html('');\r\n");
      out.write("\r\n");
      out.write("									let table = \"\";\r\n");
      out.write("\r\n");
      out.write("									for (let i = 0; i < res.length; i++) {\r\n");
      out.write("\r\n");
      out.write("										table += '<br>';\r\n");
      out.write("										table += '<table width=\"450\" height=\"100\" align=\"center\">';\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										table += '<td><h3>' + res[i].tb_title\r\n");
      out.write("												+ '<h3></td>';\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("										if (res[i].tb_file == null) {\r\n");
      out.write("											table += '<th><img src=\"./phm_img/No_Image.png\" width=\"300\", height=\"200\" align=\"center\" onClick='\r\n");
      out.write("													+ \"'snsPost()'\"\r\n");
      out.write("													+ ' style=\"cursor:pointer; border:1px solid #c8c8c8;\"></th>';\r\n");
      out.write("										} else {\r\n");
      out.write("											table += '<th><a href=\"tm_SelectOne?tb_seq='\r\n");
      out.write("													+ res[i].tb_seq\r\n");
      out.write("													+ '\"><img src=\"tm_upload/' + res[i].tb_file + '\" width=\"300\", height=\"200\" align=\"center\" style=\"cursor:pointer;\"></a></th>';\r\n");
      out.write("										}\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										table += '<td style=\"color:grey\">조회수 : '\r\n");
      out.write("												+ res[i].tb_cnt + '</td>';\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										table += '<td style=\"color:grey\">좋아요 : '\r\n");
      out.write("												+ res[i].tb_likes + '</td>'\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("										table += '</table>';\r\n");
      out.write("										table += '<br>';\r\n");
      out.write("										table += '<hr width=\"450\" align=\"center\">';\r\n");
      out.write("\r\n");
      out.write("									}\r\n");
      out.write("									$('.side_three').append(table);\r\n");
      out.write("								}\r\n");
      out.write("							},\r\n");
      out.write("							error : function() {\r\n");
      out.write("								alert('검색실패');\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function snsDetail() {\r\n");
      out.write("			$\r\n");
      out.write("					.ajax({\r\n");
      out.write("						url : 'snsDetailCon',\r\n");
      out.write("						type : 'get',\r\n");
      out.write("						data : {\r\n");
      out.write("							'user_id' : $('#user_id').text()\r\n");
      out.write("						},\r\n");
      out.write("						dataType : 'json',\r\n");
      out.write("						success : function(res) {\r\n");
      out.write("\r\n");
      out.write("							image = $('#user_image').html();\r\n");
      out.write("							nickname = $('#user_nickname').text();\r\n");
      out.write("							follow = $('#user_follow').text();\r\n");
      out.write("							follower = $('#user_follower').text();\r\n");
      out.write("							console.log($('#user_id').text())\r\n");
      out.write("\r\n");
      out.write("							let table = \"\";\r\n");
      out.write("\r\n");
      out.write("							table += '<br>';\r\n");
      out.write("							table += '<table width=\"300\" height=\"100\" align=\"center\">';\r\n");
      out.write("							table += '<th rowspan=\"4\">' + image + '</th>';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td>닉네임</td>'\r\n");
      out.write("							table += '<td><b>' + nickname + '</b></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td>팔로우</td>'\r\n");
      out.write("							table += '<td><b>' + follow + '</b></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '<tr>';\r\n");
      out.write("							table += '<td>팔로워</td>'\r\n");
      out.write("							table += '<td><b>' + follower + '</b></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							table += '</table>';\r\n");
      out.write("							table += '<br>';\r\n");
      out.write("							table += '<hr width=\"450\" align=\"center\">';\r\n");
      out.write("							table += '<br>';\r\n");
      out.write("							console.log(res);\r\n");
      out.write("							let cnt = 0;\r\n");
      out.write("							let max = -1;\r\n");
      out.write("\r\n");
      out.write("							if (res == \"\") {\r\n");
      out.write("\r\n");
      out.write("								table += '<h3 align=\"center\">등록된 게시물이 없습니다.</h3>'\r\n");
      out.write("\r\n");
      out.write("							} else {\r\n");
      out.write("\r\n");
      out.write("								table += '<table width=\"390\" height=\"100\" align=\"center\">';\r\n");
      out.write("								for (let i = 0; i < res.length; i++) {\r\n");
      out.write("									if ((i % 3) == 0) {\r\n");
      out.write("										table += '<tr>';\r\n");
      out.write("										max += 3;\r\n");
      out.write("									}\r\n");
      out.write("									table += '<td><a href=\"tm_SelectOne?tb_seq='\r\n");
      out.write("											+ res[i].tb_seq\r\n");
      out.write("											+ '\"><img src=\"tm_upload/' + res[i].tb_file+ '\" width=\"130\" height=\"130\"></a></td>';\r\n");
      out.write("									if (cnt == max) {\r\n");
      out.write("										table += '</tr>';\r\n");
      out.write("									}\r\n");
      out.write("									cnt += 1;\r\n");
      out.write("								}\r\n");
      out.write("								table += '</table>';\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("							$('.side_three').html('');\r\n");
      out.write("\r\n");
      out.write("							$('.side_three').append(table);\r\n");
      out.write("\r\n");
      out.write("						},\r\n");
      out.write("						error : function() {\r\n");
      out.write("							alert('진입실패');\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- map--------------- ------------------------------------------------------------------------------------------------------------------------------------ -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\"\r\n");
      out.write("		src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=31e189d0d305a85663770a625b11688d&libraries=services\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		var mapContainer = document.getElementById('map'); // 지도를 표시할 div \r\n");
      out.write("		mapOption = {\r\n");
      out.write("			center : new kakao.maps.LatLng(35.11070531999631,\r\n");
      out.write("					126.87780481325912), // 지도의 중심좌표 - 스마트인재개발원\r\n");
      out.write("			level : 3\r\n");
      out.write("		// 지도의 확대 레벨\r\n");
      out.write("		};\r\n");
      out.write("		// 지도를 생성합니다    \r\n");
      out.write("		var map = new kakao.maps.Map(mapContainer, mapOption);\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
