/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-04 06:04:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.commentDAO.commentDAO;
import com.memberDTO.tm_memberDTO;
import java.util.ArrayList;
import com.memberDAO.tm_memberDAO;
import com.snsDTO.tm_snsDTO;
import com.snsDAO.tm_snsDAO;

public final class N6_005fpost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.snsDAO.tm_snsDAO");
    _jspx_imports_classes.add("com.memberDAO.tm_memberDAO");
    _jspx_imports_classes.add("com.snsDTO.tm_snsDTO");
    _jspx_imports_classes.add("com.commentDAO.commentDAO");
    _jspx_imports_classes.add("com.memberDTO.tm_memberDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>N6_post</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./assets/css/N6_post.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		tm_snsDAO snsdao = new tm_snsDAO();
	tm_snsDTO snsdto = new tm_snsDTO();
	tm_memberDAO memberdao = new tm_memberDAO();
	ArrayList<String> imgList = new ArrayList<String>();
	snsdto = (tm_snsDTO) request.getAttribute("dto");
	tm_memberDTO memberdto = (tm_memberDTO) session.getAttribute("dto");
	commentDAO commentdao = new commentDAO();
	//ArrayList<commentDTO> list = commentdao.allComment();
	
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"item1\">\r\n");
      out.write("			<div>\r\n");
      out.write("				<img src=\"tm_upload/");
      out.print(snsdto.getTb_file());
      out.write("\">\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"item2\">\r\n");
      out.write("			<div class=\"item3\">\r\n");
      out.write("				<a href=\"#\" class=\"profile_img\"><img\r\n");
      out.write("					src=\"tm_upload/");
      out.print(memberdao.imgMemberSelect(snsdto.getMb_id()));
      out.write("\"></a>\r\n");
      out.write("				<a href=\"tm_selectMember?mb_id=");
      out.print(snsdto.getMb_id());
      out.write("\"\r\n");
      out.write("					class=\"user_nick\">");
      out.print(snsdto.getMb_id());
      out.write("</a> \r\n");
      out.write("				<div style=\"float:right; margin:20px; margin-top:40px;\">\r\n");
      out.write("					<a href=\"N_travelplanCon?mb_id=");
      out.print(snsdto.getMb_id());
      out.write("&t_title=");
      out.print(snsdto.getT_title() );
      out.write("\" class=\"travel_plan\">TravelPlan</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"item4\" style=\"height:10%;\">");
      out.print(snsdto.getT_title());
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"item5\" style=\"height:71.8%;\">\r\n");
      out.write("				<div id=\"tailList\">");
      out.print(snsdto.getTb_content());
      out.write("</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"item6\" style=\"height:10%;\">\r\n");
      out.write("				<button id=\"likesButton\" onclick=\"likes()\">\r\n");
      out.write("					<img src=\"img/heart_tung.png\">\r\n");
      out.write("				</button>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"likes\" style=\"align-self: center\">\r\n");
      out.write("					");
      out.print(snsdto.getTb_likes());
      out.write("</div>\r\n");
      out.write("				<button>\r\n");
      out.write("					<img src=\"img/details.png\">\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!--  <div class=\"item7\">\r\n");
      out.write("				<input id=\"commContent\" type=\"text\">\r\n");
      out.write("				<button id=\"sendTail\" onclick=\"sendTail()\">댓글달기</button>\r\n");
      out.write("			</div>-->\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function likes() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"likesCon\",\r\n");
      out.write("				type : \"post\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"tb_seq\" :\r\n");
      out.write("	");
      out.print(snsdto.getTb_seq());
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("				success : function(res) {\r\n");
      out.write("					console.log(res);\r\n");
      out.write("					$('#likes').text(res);\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"요청 실패 !\");\r\n");
      out.write("				},\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function sendTail() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("\r\n");
      out.write("				url : \"commentCon\",\r\n");
      out.write("				type : \"get\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"commContent\" : $('#commContent').val(),\r\n");
      out.write("					\"mb_id\" : $('.user_nick').text(),\r\n");
      out.write("					\"tb_seq\" :\r\n");
      out.write("	");
      out.print(snsdto.getTb_seq());
      out.write("\r\n");
      out.write("		},\r\n");
      out.write("				dataType : 'json',\r\n");
      out.write("				success : function(res) {\r\n");
      out.write("					console.log(res);\r\n");
      out.write("					console.log(res[0].mb_id);\r\n");
      out.write("					console.log(res[0].comm_content);\r\n");
      out.write("					$('#tailList').append(res[0].mb_id + '  :  ');\r\n");
      out.write("					$('#tailList').append(res[0].comm_content);\r\n");
      out.write("					$('#tailList').append('<b>');\r\n");
      out.write("\r\n");
      out.write("				},\r\n");
      out.write("				error : function() {\r\n");
      out.write("					alert(\"요청 실패!!!\")\r\n");
      out.write("\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
